// Axes high damage, slow attack speed, melee range, high crit chance
//addItem(2, {'slot': 'weapon', 'type': 'axe',  'name': 'Worn Hatchet', 'bonuses': {'+minPhysicalDamage': 13, '+maxPhysicalDamage': 19,  '+attackSpeed': 0.6,'+weaponRange': 1.4, '+critChance': 0.04 }, 'icon': 'axe'});
addItem(6, {'slot': 'weapon', 'type': 'axe',  'name': 'Hatchet', 'bonuses': {'+minPhysicalDamage': 42, '+maxPhysicalDamage': 62,  '+attackSpeed': 0.9,'+weaponRange': 1.5, '+critChance': 0.05 }, 'icon': 'axe'});
addItem(11, {'slot': 'weapon', 'type': 'axe',  'name': 'Climbing Axe', 'bonuses': {'+minPhysicalDamage': 76, '+maxPhysicalDamage': 114,  '+attackSpeed': 0.9,'+weaponRange': 1.5, '+critChance': 0.05 }, 'icon': 'axe'});
addItem(16, {'slot': 'weapon', 'type': 'axe',  'name': 'Tomahawk', 'bonuses': {'+minPhysicalDamage': 98, '+maxPhysicalDamage': 146,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(21, {'slot': 'weapon', 'type': 'axe',  'name': 'Sagaris', 'bonuses': {'+minPhysicalDamage': 128, '+maxPhysicalDamage': 192,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(26, {'slot': 'weapon', 'type': 'axe',  'name': 'Iron Battle Axe', 'bonuses': {'+minPhysicalDamage': 158, '+maxPhysicalDamage': 238,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(31, {'slot': 'weapon', 'type': 'axe',  'name': 'Black Battle Axe', 'bonuses': {'+minPhysicalDamage': 188, '+maxPhysicalDamage': 282,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(36, {'slot': 'weapon', 'type': 'axe',  'name': 'Forged Battle Axe', 'bonuses': {'+minPhysicalDamage': 218, '+maxPhysicalDamage': 328,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(41, {'slot': 'weapon', 'type': 'axe',  'name': 'Steel Battle Axe', 'bonuses': {'+minPhysicalDamage': 249, '+maxPhysicalDamage': 373,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(46, {'slot': 'weapon', 'type': 'axe',  'name': 'Etched Battle Axe', 'bonuses': {'+minPhysicalDamage': 279, '+maxPhysicalDamage': 419,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(51, {'slot': 'weapon', 'type': 'axe',  'name': 'Meteoric Battle Axe', 'bonuses': {'+minPhysicalDamage': 309, '+maxPhysicalDamage': 463,  '+attackSpeed': 1,'+weaponRange': 1.6, '+critChance': 0.06 }, 'icon': 'axe'});
addItem(61, {'slot': 'weapon', 'type': 'axe',  'name': 'Runed Battle Axe', 'bonuses': {'+minPhysicalDamage': 336, '+maxPhysicalDamage': 504,  '+attackSpeed': 1,'+weaponRange': 1.7, '+critChance': 0.07, '+minMagicDamage': 11, '+maxMagicDamage': 17 }, 'icon': 'axe'});
addItem(71, {'slot': 'weapon', 'type': 'axe',  'name': 'Admantine Battle Axe', 'bonuses': {'+minPhysicalDamage': 519, '+maxPhysicalDamage': 779,  '+attackSpeed': 0.8,'+weaponRange': 2, '+critChance': 0.1, '+minMagicDamage': 28, '+maxMagicDamage': 38 }, 'icon': 'axe'});

//Swords medium damage, medium attack speed, melee range, medium crit chance
addItem(5, {'slot': 'weapon', 'type': 'sword',  'name': 'Gladius', 'bonuses': {'+minPhysicalDamage': 38, '+maxPhysicalDamage': 58,  '+attackSpeed': 1,'+weaponRange': 1.5, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(10, {'slot': 'weapon', 'type': 'sword',  'name': 'Short Sword', 'bonuses': {'+minPhysicalDamage': 58, '+maxPhysicalDamage': 86,  '+attackSpeed': 1.2,'+weaponRange': 1.5, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(15, {'slot': 'weapon', 'type': 'sword',  'name': 'Falchion', 'bonuses': {'+minPhysicalDamage': 66, '+maxPhysicalDamage': 100,  '+attackSpeed': 1.5,'+weaponRange': 1.8, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(20, {'slot': 'weapon', 'type': 'sword',  'name': 'Scimitar', 'bonuses': {'+minPhysicalDamage': 86, '+maxPhysicalDamage': 130,  '+attackSpeed': 1.5,'+weaponRange': 1.8, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(25, {'slot': 'weapon', 'type': 'sword',  'name': 'Wakizashi', 'bonuses': {'+minPhysicalDamage': 101, '+maxPhysicalDamage': 151,  '+attackSpeed': 1.6,'+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(30, {'slot': 'weapon', 'type': 'sword',  'name': 'Longsword', 'bonuses': {'+minPhysicalDamage': 120, '+maxPhysicalDamage': 180,  '+attackSpeed': 1.6,'+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(35, {'slot': 'weapon', 'type': 'sword',  'name': 'Estoic', 'bonuses': {'+minPhysicalDamage': 139, '+maxPhysicalDamage': 209,  '+attackSpeed': 1.6,'+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(40, {'slot': 'weapon', 'type': 'sword',  'name': 'Broadsword', 'bonuses': {'+minPhysicalDamage': 158, '+maxPhysicalDamage': 238,  '+attackSpeed': 1.6,'+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'sword'});
addItem(45, {'slot': 'weapon', 'type': 'sword',  'name': 'Bastardsword', 'bonuses': {'+minPhysicalDamage': 176, '+maxPhysicalDamage': 264,  '+attackSpeed': 1.6,'+weaponRange': 2.3, '+critChance': 0.05 }, 'icon': 'sword'});
addItem(50, {'slot': 'weapon', 'type': 'sword',  'name': 'Meteoric Saber', 'bonuses': {'+minPhysicalDamage': 173, '+maxPhysicalDamage': 259,  '+attackSpeed': 1.8,'+weaponRange': 2.3, '+critChance': 0.05 }, 'icon': 'sword'});
addItem(60, {'slot': 'weapon', 'type': 'sword',  'name': 'Runed Saber', 'bonuses': {'+minPhysicalDamage': 190, '+maxPhysicalDamage': 286,  '+attackSpeed': 1.8,'+weaponRange': 2.3, '+critChance': 0.05, '+minMagicDamage': 6, '+maxMagicDamage': 8 }, 'icon': 'sword'});
addItem(70, {'slot': 'weapon', 'type': 'sword',  'name': 'Etched Dragon Horn', 'bonuses': {'+minPhysicalDamage': 198, '+maxPhysicalDamage': 298,  '+attackSpeed': 1.9,'+weaponRange': 2.5, '+critChance': 0.06, '+minMagicDamage': 10, '+maxMagicDamage': 14 }, 'icon': 'sword'});

//Daggers low damage, high attack speed, melee range, low crit chance
addItem(3, {'slot': 'weapon', 'type': 'dagger',  'name': 'Pugio', 'bonuses': {'+minPhysicalDamage': 26, '+maxPhysicalDamage': 38,  '+attackSpeed': 1.5,'+weaponRange': 1.2, '+critChance': 0.03}, 'icon': 'dagger'});
addItem(8, {'slot': 'weapon', 'type': 'dagger',  'name': 'Hewing Knife', 'bonuses': {'+minPhysicalDamage': 46, '+maxPhysicalDamage': 70,  '+attackSpeed': 1.5,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(13, {'slot': 'weapon', 'type': 'dagger',  'name': 'Cross-hilt Dagger', 'bonuses': {'+minPhysicalDamage': 67, '+maxPhysicalDamage': 101,  '+attackSpeed': 1.5,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(18, {'slot': 'weapon', 'type': 'dagger',  'name': 'Tanto', 'bonuses': {'+minPhysicalDamage': 82, '+maxPhysicalDamage': 124,  '+attackSpeed': 1.6,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(23, {'slot': 'weapon', 'type': 'dagger',  'name': 'Stiletto', 'bonuses': {'+minPhysicalDamage': 102, '+maxPhysicalDamage': 152,  '+attackSpeed': 1.6,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(28, {'slot': 'weapon', 'type': 'dagger',  'name': 'Steel Dirk', 'bonuses': {'+minPhysicalDamage': 107, '+maxPhysicalDamage': 161,  '+attackSpeed': 1.8,'+weaponRange': 1.5, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(33, {'slot': 'weapon', 'type': 'dagger',  'name': 'Stainless Dirk', 'bonuses': {'+minPhysicalDamage': 125, '+maxPhysicalDamage': 187,  '+attackSpeed': 1.8,'+weaponRange': 1.5, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(38, {'slot': 'weapon', 'type': 'dagger',  'name': 'Serrated Dirk', 'bonuses': {'+minPhysicalDamage': 142, '+maxPhysicalDamage': 212,  '+attackSpeed': 1.8,'+weaponRange': 1.5, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(43, {'slot': 'weapon', 'type': 'dagger',  'name': 'Masterful Dirk', 'bonuses': {'+minPhysicalDamage': 159, '+maxPhysicalDamage': 239,  '+attackSpeed': 1.8,'+weaponRange': 1.5, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(48, {'slot': 'weapon', 'type': 'dagger',  'name': 'Meteoric Dirk', 'bonuses': {'+minPhysicalDamage': 159, '+maxPhysicalDamage': 239,  '+attackSpeed': 2,'+weaponRange': 1.5, '+critChance': 0.03 }, 'icon': 'dagger'});
addItem(58, {'slot': 'weapon', 'type': 'dagger',  'name': 'Runed Dirk', 'bonuses': {'+minPhysicalDamage': 174, '+maxPhysicalDamage': 262,  '+attackSpeed': 2,'+weaponRange': 1.5, '+critChance': 0.03, '+minMagicDamage': 6, '+maxMagicDamage': 7 }, 'icon': 'dagger'});
addItem(68, {'slot': 'weapon', 'type': 'dagger',  'name': 'Etched Dragon Fang', 'bonuses': {'+minPhysicalDamage': 190, '+maxPhysicalDamage': 286,  '+attackSpeed': 2,'+weaponRange': 1.8, '+critChance': 0.05, '+minMagicDamage': 9, '+maxMagicDamage': 13 }, 'icon': 'dagger'});

//Fists low damage, high attack speed, melee range, low crit chance
addItem(1, {'slot': 'weapon', 'type': 'fist',  'name': 'Rock', 'bonuses': {'+minPhysicalDamage': 4, '+maxPhysicalDamage': 6,  '+attackSpeed': 1.5,'+weaponRange': 1, '+critChance': 0.03 }, 'icon': 'fists'});
addItem(2, {'slot': 'weapon', 'type': 'fist',  'name': 'Cestus', 'bonuses': {'+minPhysicalDamage': 14, '+maxPhysicalDamage': 20,  '+attackSpeed': 1.6,'+weaponRange': 1, '+critChance': 0.03 }, 'icon': 'fists'});
addItem(7, {'slot': 'weapon', 'type': 'fist',  'name': 'Bronze Weights', 'bonuses': {'+minPhysicalDamage': 43, '+maxPhysicalDamage': 65,  '+attackSpeed': 1.6,'+weaponRange': 1, '+critChance': 0.03 }, 'icon': 'fists'});
addItem(12, {'slot': 'weapon', 'type': 'fist',  'name': 'Iron Weights', 'bonuses': {'+minPhysicalDamage': 62, '+maxPhysicalDamage': 94,  '+attackSpeed': 1.6,'+weaponRange': 1, '+critChance': 0.03 }, 'icon': 'fists'});
addItem(17, {'slot': 'weapon', 'type': 'fist',  'name': 'Tekko', 'bonuses': {'+minPhysicalDamage': 73, '+maxPhysicalDamage': 109,  '+attackSpeed': 1.8,'+weaponRange': 1.1, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(22, {'slot': 'weapon', 'type': 'fist',  'name': 'Iron Knuckles', 'bonuses': {'+minPhysicalDamage': 90, '+maxPhysicalDamage': 136,  '+attackSpeed': 1.8,'+weaponRange': 1.1, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(27, {'slot': 'weapon', 'type': 'fist',  'name': 'Steel Knuckles', 'bonuses': {'+minPhysicalDamage': 107, '+maxPhysicalDamage': 161,  '+attackSpeed': 1.8,'+weaponRange': 1.1, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(32, {'slot': 'weapon', 'type': 'fist',  'name': 'Spiked Knuckles', 'bonuses': {'+minPhysicalDamage': 112, '+maxPhysicalDamage': 168,  '+attackSpeed': 2,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(37, {'slot': 'weapon', 'type': 'fist',  'name': 'Steel Claws', 'bonuses': {'+minPhysicalDamage': 128, '+maxPhysicalDamage': 192,  '+attackSpeed': 2,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(42, {'slot': 'weapon', 'type': 'fist',  'name': 'Masterful Claws', 'bonuses': {'+minPhysicalDamage': 143, '+maxPhysicalDamage': 215,  '+attackSpeed': 2,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(47, {'slot': 'weapon', 'type': 'fist',  'name': 'Meteoric Claws', 'bonuses': {'+minPhysicalDamage': 159, '+maxPhysicalDamage': 239,  '+attackSpeed': 2,'+weaponRange': 1.2, '+critChance': 0.03 }, 'icon': 'knuckles'});
addItem(57, {'slot': 'weapon', 'type': 'fist',  'name': 'Runed Claws', 'bonuses': {'+minPhysicalDamage': 139, '+maxPhysicalDamage': 209,  '+attackSpeed': 2.5,'+weaponRange': 1.2, '+critChance': 0.03, '+minMagicDamage': 4, '+maxMagicDamage': 6 }, 'icon': 'knuckles'});
addItem(67, {'slot': 'weapon', 'type': 'fist',  'name': 'Adamantine Claws', 'bonuses': {'+minPhysicalDamage': 256, '+maxPhysicalDamage': 384,  '+attackSpeed': 1.7,'+weaponRange': 1.4, '+critChance': 0.04, '+minMagicDamage': 13, '+maxMagicDamage': 19 }, 'icon': 'knuckles'});

//Wands magic damage, medium attack speed, medium range, low crit chance
addItem(1, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Stick', 'bonuses': {'+minMagicDamage': 6, '+maxMagicDamage': 10,  '+attackSpeed': 1,'+weaponRange': 7, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(5, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Balsa Wand', 'bonuses': {'+minMagicDamage': 14, '+maxMagicDamage': 22,  '+attackSpeed': 1.3,'+weaponRange': 7, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(10, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Juniper Wand', 'bonuses': {'+minMagicDamage': 25, '+maxMagicDamage': 37,  '+attackSpeed': 1.4,'+weaponRange': 7, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(15, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Pine Wand', 'bonuses': {'+minMagicDamage': 34, '+maxMagicDamage': 50,  '+attackSpeed': 1.5,'+weaponRange': 8, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(20, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Rosewood Wand', 'bonuses': {'+minMagicDamage': 44, '+maxMagicDamage': 66,  '+attackSpeed': 1.5,'+weaponRange': 8, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(25, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Rowan Wand', 'bonuses': {'+minMagicDamage': 50, '+maxMagicDamage': 76,  '+attackSpeed': 1.5,'+weaponRange': 9, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(30, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Oak Wand', 'bonuses': {'+minMagicDamage': 60, '+maxMagicDamage': 90,  '+attackSpeed': 1.6,'+weaponRange': 9, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(35, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Ebony Wand', 'bonuses': {'+minMagicDamage': 70, '+maxMagicDamage': 104,  '+attackSpeed': 1.6,'+weaponRange': 10, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(40, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Ironwood Wand', 'bonuses': {'+minMagicDamage': 80, '+maxMagicDamage': 120,  '+attackSpeed': 1.6,'+weaponRange': 10, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(45, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Intricate Wand', 'bonuses': {'+minMagicDamage': 79, '+maxMagicDamage': 119,  '+attackSpeed': 1.8,'+weaponRange': 11, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(50, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Runed Wand', 'bonuses': {'+minMagicDamage':88, '+maxMagicDamage': 132,  '+attackSpeed': 1.8,'+weaponRange': 11, '+critChance': 0.03 }, 'icon': 'wand'});
addItem(60, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Adamantine Wand', 'bonuses': {'+minMagicDamage': 194, '+maxMagicDamage': 290,  '+attackSpeed': 1,'+weaponRange': 12, '+critChance': 0.03, '+minPhysicalDamage': 26, '+maxPhysicalDamage': 38 }, 'icon': 'wand'});
addItem(70, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Orichalcum Wand', 'bonuses': {'+minMagicDamage': 101, '+maxMagicDamage': 151,  '+attackSpeed': 1.9,'+weaponRange': 14, '+critChance': 0.04, '+minPhysicalDamage': 20, '+maxPhysicalDamage': 30 }, 'icon': 'wand'});

//Thrown medium damage, medium attack speed, medium range, medium crit chance
addItem(1, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Ball', 'bonuses': {'+minPhysicalDamage': 3, '+maxPhysicalDamage': 5,  '+attackSpeed': 1.1,'+weaponRange': 8, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(4, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Pilum', 'bonuses': {'+minPhysicalDamage': 34, '+maxPhysicalDamage': 52,  '+attackSpeed': 1.1,'+weaponRange': 9, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(9, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Knife', 'bonuses': {'+minPhysicalDamage': 58, '+maxPhysicalDamage': 86,  '+attackSpeed': 1.2,'+weaponRange': 9, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(14, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Club', 'bonuses': {'+minPhysicalDamage': 83, '+maxPhysicalDamage': 125,  '+attackSpeed': 1.2,'+weaponRange': 10, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(19, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Axe', 'bonuses': {'+minPhysicalDamage': 109, '+maxPhysicalDamage': 163,  '+attackSpeed': 1.2,'+weaponRange': 10, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(24, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Shuriken', 'bonuses': {'+minPhysicalDamage': 80, '+maxPhysicalDamage': 120,  '+attackSpeed': 2,'+weaponRange': 11, '+critChance': 0.04 }, 'icon': 'shuriken'});
addItem(29, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Bolas', 'bonuses': {'+minPhysicalDamage': 120, '+maxPhysicalDamage': 180,  '+attackSpeed': 1.6,'+weaponRange': 11, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(34, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Chakram', 'bonuses': {'+minPhysicalDamage': 139, '+maxPhysicalDamage': 209,  '+attackSpeed': 1.6,'+weaponRange': 12, '+critChance': 0.04 }, 'icon': 'shuriken'});
addItem(39, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Javelin', 'bonuses': {'+minPhysicalDamage': 141, '+maxPhysicalDamage': 211,  '+attackSpeed': 1.8,'+weaponRange': 12, '+critChance': 0.04 }, 'icon': 'throwing'});
addItem(44, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Heavy Javelin', 'bonuses': {'+minPhysicalDamage': 187, '+maxPhysicalDamage': 281,  '+attackSpeed': 1.5,'+weaponRange': 13, '+critChance': 0.05 }, 'icon': 'throwing'});
addItem(49, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Meteoric Javelin', 'bonuses': {'+minPhysicalDamage': 208, '+maxPhysicalDamage': 312,  '+attackSpeed': 1.5,'+weaponRange': 13, '+critChance': 0.05 }, 'icon': 'throwing'});
addItem(59, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Runed Javelin', 'bonuses': {'+minPhysicalDamage': 190, '+maxPhysicalDamage': 286,  '+attackSpeed': 1.8,'+weaponRange': 14, '+critChance': 0.05, '+minMagicDamage': 6, '+maxMagicDamage': 8 }, 'icon': 'throwing'});
addItem(69, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Adamantine Javelin', 'bonuses': {'+minPhysicalDamage': 415, '+maxPhysicalDamage': 623,  '+attackSpeed': 1,'+weaponRange': 15, '+critChance': 0.07, '+minMagicDamage': 20, '+maxMagicDamage': 30 }, 'icon': 'throwing'});

// Two handed ranged weapons, Bows and Crossbows.
addItem(2, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Primitive Bow', 'bonuses': {'+minPhysicalDamage': 14, '+maxPhysicalDamage': 16,  '+attackSpeed': 1, '+weaponRange': 9, '+critChance': 0.03 }, 'icon': 'bow'});
addItem(7, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Short Bow', 'bonuses': {'+minPhysicalDamage': 60, '+maxPhysicalDamage': 70,  '+attackSpeed': 1.1, '+weaponRange': 10, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(12, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Recurve Bow', 'bonuses': {'+minPhysicalDamage': 110, '+maxPhysicalDamage': 126,  '+attackSpeed': 1.1, '+weaponRange': 12, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(17, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Long Bow', 'bonuses': {'+minPhysicalDamage': 174, '+maxPhysicalDamage': 200,  '+attackSpeed': 1, '+weaponRange': 14, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(22, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Crossbow', 'bonuses': {'+minPhysicalDamage': 228, '+maxPhysicalDamage': 262,  '+attackSpeed': 1, '+weaponRange': 13, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(27, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Composite Bow', 'bonuses': {'+minPhysicalDamage': 256, '+maxPhysicalDamage': 294,  '+attackSpeed': 1.1, '+weaponRange': 14, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(32, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Repeating Crossbow', 'bonuses': {'+minPhysicalDamage': 168, '+maxPhysicalDamage': 192,  '+attackSpeed': 2, '+weaponRange': 12, '+critChance': 0.04 }, 'icon': 'bow'});
addItem(37, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Recurve Crossbow', 'bonuses': {'+minPhysicalDamage': 350, '+maxPhysicalDamage': 402,  '+attackSpeed': 1.1, '+weaponRange': 14, '+critChance': 0.05 }, 'icon': 'bow'});
addItem(42, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Arbalest', 'bonuses': {'+minPhysicalDamage': 439, '+maxPhysicalDamage': 503,  '+attackSpeed': 1, '+weaponRange': 17, '+critChance': 0.05 }, 'icon': 'bow'});
addItem(47, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Compound Bow', 'bonuses': {'+minPhysicalDamage': 410, '+maxPhysicalDamage': 470,  '+attackSpeed': 1.2, '+weaponRange': 18, '+critChance': 0.05 }, 'icon': 'bow'});
addItem(52, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Compound Crossbow', 'bonuses': {'+minPhysicalDamage': 544, '+maxPhysicalDamage': 626,  '+attackSpeed': 1, '+weaponRange': 18, '+critChance': 0.05 }, 'icon': 'bow'});
addItem(62, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Adamantine Crossbow', 'bonuses': {'+minPhysicalDamage': 845, '+maxPhysicalDamage': 973,  '+attackSpeed': 0.8, '+weaponRange': 20, '+critChance': 0.06, '+minMagicDamage': 26, '+maxMagicDamage': 40 }, 'icon': 'bow'});
addItem(72, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Dragonbone Greatbow', 'bonuses': {'+minPhysicalDamage': 657, '+maxPhysicalDamage': 757,  '+attackSpeed': 1, '+weaponRange': 20, '+critChance': 0.06, '+minMagicDamage': 38, '+maxMagicDamage': 56 }, 'icon': 'bow'});

//Staffs
//addItem(2, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Branch', 'bonuses': {'+minPhysicalDamage': 5, '+maxPhysicalDamage': 7, '+minMagicDamage': 2, '+maxMagicDamage': 4, '+attackSpeed': 1, '+weaponRange': 1.8, '+critChance': 0.03 }, 'icon': 'staff'});
addItem(3, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Balsa Staff', 'bonuses': {'+minPhysicalDamage': 26, '+maxPhysicalDamage': 30, '+minMagicDamage': 13, '+maxMagicDamage': 15, '+attackSpeed': 1.2, '+weaponRange': 2, '+critChance': 0.03 }, 'icon': 'staff'});
addItem(8, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Juniper Staff', 'bonuses': {'+minPhysicalDamage': 45, '+maxPhysicalDamage': 55, '+minMagicDamage': 23, '+maxMagicDamage': 27, '+attackSpeed': 1.2, '+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'staff'});
addItem(13, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Pine Staff', 'bonuses': {'+minPhysicalDamage': 65, '+maxPhysicalDamage': 79, '+minMagicDamage': 33, '+maxMagicDamage': 39, '+attackSpeed': 1.2, '+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'staff'});
addItem(18, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Rosewood Quarterstaff', 'bonuses': {'+minPhysicalDamage': 86, '+maxPhysicalDamage': 104, '+minMagicDamage': 43, '+maxMagicDamage': 51, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.04 }, 'icon': 'staff'});
addItem(23, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Rowan Quarterstaff', 'bonuses': {'+minPhysicalDamage': 106, '+maxPhysicalDamage': 128, '+minMagicDamage': 53, '+maxMagicDamage': 63, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.04 }, 'icon': 'staff'});
addItem(28, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Oak Quarterstaff', 'bonuses': {'+minPhysicalDamage': 126, '+maxPhysicalDamage': 154, '+minMagicDamage': 63, '+maxMagicDamage': 77, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.04 }, 'icon': 'staff'});
addItem(33, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Ebony Quarterstaff', 'bonuses': {'+minPhysicalDamage': 145, '+maxPhysicalDamage': 177, '+minMagicDamage': 72, '+maxMagicDamage': 88, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.05 }, 'icon': 'staff'});
addItem(38, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Ironwood Quarterstaff', 'bonuses': {'+minPhysicalDamage': 165, '+maxPhysicalDamage': 201, '+minMagicDamage': 82, '+maxMagicDamage': 100, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.05 }, 'icon': 'staff'});
addItem(43, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Iron Quarterstaff', 'bonuses': {'+minPhysicalDamage': 183, '+maxPhysicalDamage': 223, '+minMagicDamage': 91, '+maxMagicDamage': 111, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.06 }, 'icon': 'staff'});
addItem(48, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Steel Quarterstaff', 'bonuses': {'+minPhysicalDamage': 203, '+maxPhysicalDamage': 247, '+minMagicDamage': 101, '+maxMagicDamage': 123, '+attackSpeed': 1.2, '+weaponRange': 2.5, '+critChance': 0.06 }, 'icon': 'staff'});
addItem(58, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Adamantine Quarterstaff', 'bonuses': {'+minPhysicalDamage': 331, '+maxPhysicalDamage': 403, '+minMagicDamage': 168, '+maxMagicDamage': 204, '+attackSpeed': 0.9, '+weaponRange': 3, '+critChance': 0.07 }, 'icon': 'staff'});
addItem(68, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Orichalcum Quarterstaff', 'bonuses': {'+minPhysicalDamage': 225, '+maxPhysicalDamage': 273, '+minMagicDamage': 112, '+maxMagicDamage': 136, '+attackSpeed': 1.5, '+weaponRange': 3, '+critChance': 0.07 }, 'icon': 'staff'});

//Two Handed Axes and Polearms
addItem(2, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Pickaxe', 'bonuses': {'+minPhysicalDamage': 25, '+maxPhysicalDamage': 31,  '+attackSpeed': 0.5, '+weaponRange': 2, '+critChance': 0.05 }, 'icon': 'greatAxe'});
addItem(7, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Felling Axe', 'bonuses': {'+minPhysicalDamage': 79, '+maxPhysicalDamage': 97,  '+attackSpeed': 0.8, '+weaponRange': 2, '+critChance': 0.06 }, 'icon': 'greatAxe'});
addItem(12, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Scythe', 'bonuses': {'+minPhysicalDamage': 143, '+maxPhysicalDamage': 175,  '+attackSpeed': 0.8, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatAxe'});
addItem(17, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Greataxe', 'bonuses': {'+minPhysicalDamage': 164, '+maxPhysicalDamage': 200,  '+attackSpeed': 1, '+weaponRange': 3, '+critChance': 0.07 }, 'icon': 'greatAxe'});
addItem(22, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Heavy Greataxe', 'bonuses': {'+minPhysicalDamage': 214, '+maxPhysicalDamage': 262,  '+attackSpeed': 1, '+weaponRange': 3, '+critChance': 0.07 }, 'icon': 'greatAxe'});
addItem(27, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Naginata', 'bonuses': {'+minPhysicalDamage': 240, '+maxPhysicalDamage': 294,  '+attackSpeed': 1.1, '+weaponRange': 4, '+critChance': 0.07 }, 'icon': 'greatAxe'});
addItem(32, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Voulge', 'bonuses': {'+minPhysicalDamage': 283, '+maxPhysicalDamage': 347,  '+attackSpeed': 1.1, '+weaponRange': 4, '+critChance': 0.08 }, 'icon': 'greatAxe'});
addItem(37, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Glaive', 'bonuses': {'+minPhysicalDamage': 330, '+maxPhysicalDamage': 402,  '+attackSpeed': 1.1, '+weaponRange': 4, '+critChance': 0.08 }, 'icon': 'greatAxe'});
addItem(42, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Iron Halberd', 'bonuses': {'+minPhysicalDamage': 340, '+maxPhysicalDamage': 416,  '+attackSpeed': 1.2, '+weaponRange': 5, '+critChance': 0.09 }, 'icon': 'greatAxe'});
addItem(47, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Steel Halberd', 'bonuses': {'+minPhysicalDamage': 382, '+maxPhysicalDamage': 466,  '+attackSpeed': 1.2, '+weaponRange': 5, '+critChance': 0.09 }, 'icon': 'greatAxe'});
addItem(52, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Poleaxe', 'bonuses': {'+minPhysicalDamage': 387, '+maxPhysicalDamage': 473,  '+attackSpeed': 1.3, '+weaponRange': 6, '+critChance': 0.1 }, 'icon': 'greatAxe'});
addItem(62, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Runed Poleaxe', 'bonuses': {'+minPhysicalDamage': 425, '+maxPhysicalDamage': 519,  '+attackSpeed': 1.3, '+weaponRange': 6, '+critChance': 0.1, '+minMagicDamage': 10, '+maxMagicDamage': 24 }, 'icon': 'greatAxe'});
addItem(72, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Adamantine Poleaxe', 'bonuses': {'+minPhysicalDamage': 1014, '+maxPhysicalDamage': 1238,  '+attackSpeed': 0.7, '+weaponRange': 6, '+critChance': 0.11, '+minMagicDamage': 50, '+maxMagicDamage': 100 }, 'icon': 'greatAxe'});

//Greatswords
//addItem(2, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Corroded Claymore', 'bonuses': {'+minPhysicalDamage': 16, '+maxPhysicalDamage': 20, '+attackSpeed': 0.8, '+weaponRange': 2, '+critChance': 0.04 }, 'icon': 'greatSword'});
addItem(6, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Copper Claymore', 'bonuses': {'+minPhysicalDamage': 64, '+maxPhysicalDamage': 78, '+attackSpeed': 1, '+weaponRange': 2, '+critChance': 0.05 }, 'icon': 'greatSword'});
addItem(11, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Bronze Claymore', 'bonuses': {'+minPhysicalDamage': 116, '+maxPhysicalDamage': 140, '+attackSpeed': 1, '+weaponRange': 2, '+critChance': 0.05 }, 'icon': 'greatSword'});
addItem(16, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Iron Claymore', 'bonuses': {'+minPhysicalDamage': 167, '+maxPhysicalDamage': 203, '+attackSpeed': 1, '+weaponRange': 2, '+critChance': 0.05 }, 'icon': 'greatSword'});
addItem(21, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Black Greatsword', 'bonuses': {'+minPhysicalDamage': 180, '+maxPhysicalDamage': 220, '+attackSpeed': 1.2, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(26, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Katana', 'bonuses': {'+minPhysicalDamage': 223, '+maxPhysicalDamage': 271, '+attackSpeed': 1.2, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(31, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Forged Greatsword', 'bonuses': {'+minPhysicalDamage': 265, '+maxPhysicalDamage': 323, '+attackSpeed': 1.2, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(36, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Steel Greatsword', 'bonuses': {'+minPhysicalDamage': 307, '+maxPhysicalDamage': 375, '+attackSpeed': 1.2, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(41, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Stainless Greatsword', 'bonuses': {'+minPhysicalDamage': 350, '+maxPhysicalDamage': 428, '+attackSpeed': 1.2, '+weaponRange': 3, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(46, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Bidenhander', 'bonuses': {'+minPhysicalDamage': 336, '+maxPhysicalDamage': 410, '+attackSpeed': 1.4, '+weaponRange': 3.5, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(51, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Meteoric Bidenhander', 'bonuses': {'+minPhysicalDamage': 373, '+maxPhysicalDamage': 465, '+attackSpeed': 1.4, '+weaponRange': 3.5, '+critChance': 0.06 }, 'icon': 'greatSword'});
addItem(61, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Adamantine Bidenhander', 'bonuses': {'+minPhysicalDamage': 710, '+maxPhysicalDamage': 866, '+attackSpeed': 0.9, '+weaponRange': 3.5, '+critChance': 0.07, '+minMagicDamage': 25, '+maxMagicDamage': 33 }, 'icon': 'greatSword'});
addItem(71, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Masterwork Katana', 'bonuses': {'+minPhysicalDamage': 421, '+maxPhysicalDamage': 513, '+attackSpeed': 1.5, '+weaponRange': 4, '+critChance': 0.07, '+minMagicDamage': 26, '+maxMagicDamage': 36 }, 'icon': 'greatSword'});