// Axes high damage, slow attack speed, melee range, high crit chance
//addItem(2, {'slot': 'weapon', 'type': 'axe',  'name': 'Worn Hatchet', 'bonuses': {'+minDamage': 13, '+maxDamage': 19,  '+attackSpeed': 0.6,'+range': 1.4, '+critChance': .04 }, 'icon': 'axe'});
addItem(6, {'slot': 'weapon', 'type': 'axe',  'name': 'Hatchet', 'bonuses': {'+minDamage': 42, '+maxDamage': 62,  '+attackSpeed': 0.9,'+range': 1.5, '+critChance': .05 }, 'icon': 'axe'});
addItem(11, {'slot': 'weapon', 'type': 'axe',  'name': 'Climbing Axe', 'bonuses': {'+minDamage': 76, '+maxDamage': 114,  '+attackSpeed': 0.9,'+range': 1.5, '+critChance': .05 }, 'icon': 'axe'});
addItem(16, {'slot': 'weapon', 'type': 'axe',  'name': 'Tomahawk', 'bonuses': {'+minDamage': 98, '+maxDamage': 146,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(21, {'slot': 'weapon', 'type': 'axe',  'name': 'Sagaris', 'bonuses': {'+minDamage': 128, '+maxDamage': 192,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(26, {'slot': 'weapon', 'type': 'axe',  'name': 'Iron Battle Axe', 'bonuses': {'+minDamage': 158, '+maxDamage': 238,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(31, {'slot': 'weapon', 'type': 'axe',  'name': 'Black Battle Axe', 'bonuses': {'+minDamage': 188, '+maxDamage': 282,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(36, {'slot': 'weapon', 'type': 'axe',  'name': 'Forged Battle Axe', 'bonuses': {'+minDamage': 218, '+maxDamage': 328,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(41, {'slot': 'weapon', 'type': 'axe',  'name': 'Steel Battle Axe', 'bonuses': {'+minDamage': 249, '+maxDamage': 373,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(46, {'slot': 'weapon', 'type': 'axe',  'name': 'Etched Battle Axe', 'bonuses': {'+minDamage': 279, '+maxDamage': 419,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(51, {'slot': 'weapon', 'type': 'axe',  'name': 'Meteoric Battle Axe', 'bonuses': {'+minDamage': 309, '+maxDamage': 463,  '+attackSpeed': 1,'+range': 1.6, '+critChance': .06 }, 'icon': 'axe'});
addItem(61, {'slot': 'weapon', 'type': 'axe',  'name': 'Runed Battle Axe', 'bonuses': {'+minDamage': 336, '+maxDamage': 504,  '+attackSpeed': 1,'+range': 1.7, '+critChance': .07, '+minMagicDamage': 11, '+maxMagicDamage': 17 }, 'icon': 'axe'});
addItem(71, {'slot': 'weapon', 'type': 'axe',  'name': 'Admantine Battle Axe', 'bonuses': {'+minDamage': 519, '+maxDamage': 779,  '+attackSpeed': 0.7,'+range': 2, '+critChance': .1, '+minMagicDamage': 28, '+maxMagicDamage': 38 }, 'icon': 'axe'});

//Swords medium damage, medium attack speed, melee range, medium crit chance
addItem(5, {'slot': 'weapon', 'type': 'sword',  'name': 'Gladius', 'bonuses': {'+minDamage': 38, '+maxDamage': 58,  '+attackSpeed': 1,'+range': 1.5, '+critChance': .04 }, 'icon': 'sword'});
addItem(10, {'slot': 'weapon', 'type': 'sword',  'name': 'Short Sword', 'bonuses': {'+minDamage': 58, '+maxDamage': 86,  '+attackSpeed': 1.2,'+range': 1.5, '+critChance': .04 }, 'icon': 'sword'});
addItem(15, {'slot': 'weapon', 'type': 'sword',  'name': 'Falchion', 'bonuses': {'+minDamage': 66, '+maxDamage': 100,  '+attackSpeed': 1.5,'+range': 1.8, '+critChance': .04 }, 'icon': 'sword'});
addItem(20, {'slot': 'weapon', 'type': 'sword',  'name': 'Scimitar', 'bonuses': {'+minDamage': 86, '+maxDamage': 130,  '+attackSpeed': 1.5,'+range': 1.8, '+critChance': .04 }, 'icon': 'sword'});
addItem(25, {'slot': 'weapon', 'type': 'sword',  'name': 'Wakizashi', 'bonuses': {'+minDamage': 101, '+maxDamage': 151,  '+attackSpeed': 1.6,'+range': 2, '+critChance': .04 }, 'icon': 'sword'});
addItem(30, {'slot': 'weapon', 'type': 'sword',  'name': 'Longsword', 'bonuses': {'+minDamage': 120, '+maxDamage': 180,  '+attackSpeed': 1.6,'+range': 2, '+critChance': .04 }, 'icon': 'sword'});
addItem(35, {'slot': 'weapon', 'type': 'sword',  'name': 'Estoic', 'bonuses': {'+minDamage': 139, '+maxDamage': 209,  '+attackSpeed': 1.6,'+range': 2, '+critChance': .04 }, 'icon': 'sword'});
addItem(40, {'slot': 'weapon', 'type': 'sword',  'name': 'Broadsword', 'bonuses': {'+minDamage': 158, '+maxDamage': 238,  '+attackSpeed': 1.6,'+range': 2, '+critChance': .04 }, 'icon': 'sword'});
addItem(45, {'slot': 'weapon', 'type': 'sword',  'name': 'Bastardsword', 'bonuses': {'+minDamage': 176, '+maxDamage': 264,  '+attackSpeed': 1.6,'+range': 2.3, '+critChance': .05 }, 'icon': 'sword'});
addItem(50, {'slot': 'weapon', 'type': 'sword',  'name': 'Meteoric Saber', 'bonuses': {'+minDamage': 173, '+maxDamage': 259,  '+attackSpeed': 1.8,'+range': 2.3, '+critChance': .05 }, 'icon': 'sword'});
addItem(60, {'slot': 'weapon', 'type': 'sword',  'name': 'Runed Saber', 'bonuses': {'+minDamage': 190, '+maxDamage': 286,  '+attackSpeed': 1.8,'+range': 2.3, '+critChance': .05, '+minMagicDamage': 6, '+maxMagicDamage': 8 }, 'icon': 'sword'});
addItem(70, {'slot': 'weapon', 'type': 'sword',  'name': 'Etched Dragon Horn', 'bonuses': {'+minDamage': 198, '+maxDamage': 298,  '+attackSpeed': 1.9,'+range': 2.5, '+critChance': .06, '+minMagicDamage': 10, '+maxMagicDamage': 14 }, 'icon': 'sword'});

//Daggers low damage, high attack speed, melee range, low crit chance
addItem(3, {'slot': 'weapon', 'type': 'dagger',  'name': 'Pugio', 'bonuses': {'+minDamage': 26, '+maxDamage': 38,  '+attackSpeed': 1.5,'+range': 1.2, '+critChance': .03 }, 'icon': 'sword'});
addItem(8, {'slot': 'weapon', 'type': 'dagger',  'name': 'Hewing Knife', 'bonuses': {'+minDamage': 46, '+maxDamage': 70,  '+attackSpeed': 1.5,'+range': 1.2, '+critChance': .03 }, 'icon': 'sword'});
addItem(13, {'slot': 'weapon', 'type': 'dagger',  'name': 'Cross-hilt Dagger', 'bonuses': {'+minDamage': 67, '+maxDamage': 101,  '+attackSpeed': 1.5,'+range': 1.2, '+critChance': .03 }, 'icon': 'sword'});
addItem(18, {'slot': 'weapon', 'type': 'dagger',  'name': 'Tanto', 'bonuses': {'+minDamage': 82, '+maxDamage': 124,  '+attackSpeed': 1.6,'+range': 1.2, '+critChance': .03 }, 'icon': 'sword'});
addItem(23, {'slot': 'weapon', 'type': 'dagger',  'name': 'Stiletto', 'bonuses': {'+minDamage': 102, '+maxDamage': 152,  '+attackSpeed': 1.6,'+range': 1.2, '+critChance': .03 }, 'icon': 'sword'});
addItem(28, {'slot': 'weapon', 'type': 'dagger',  'name': 'Steel Dirk', 'bonuses': {'+minDamage': 107, '+maxDamage': 161,  '+attackSpeed': 1.8,'+range': 1.5, '+critChance': .03 }, 'icon': 'sword'});
addItem(33, {'slot': 'weapon', 'type': 'dagger',  'name': 'Stainless Dirk', 'bonuses': {'+minDamage': 125, '+maxDamage': 187,  '+attackSpeed': 1.8,'+range': 1.5, '+critChance': .03 }, 'icon': 'sword'});
addItem(38, {'slot': 'weapon', 'type': 'dagger',  'name': 'Serrated Dirk', 'bonuses': {'+minDamage': 142, '+maxDamage': 212,  '+attackSpeed': 1.8,'+range': 1.5, '+critChance': .03 }, 'icon': 'sword'});
addItem(43, {'slot': 'weapon', 'type': 'dagger',  'name': 'Masterful Dirk', 'bonuses': {'+minDamage': 159, '+maxDamage': 239,  '+attackSpeed': 1.8,'+range': 1.5, '+critChance': .03 }, 'icon': 'sword'});
addItem(48, {'slot': 'weapon', 'type': 'dagger',  'name': 'Meteoric Dirk', 'bonuses': {'+minDamage': 159, '+maxDamage': 239,  '+attackSpeed': 2,'+range': 1.5, '+critChance': .03 }, 'icon': 'sword'});
addItem(58, {'slot': 'weapon', 'type': 'dagger',  'name': 'Runed Dirk', 'bonuses': {'+minDamage': 174, '+maxDamage': 262,  '+attackSpeed': 2,'+range': 1.5, '+critChance': .03, '+minMagicDamage': 6, '+maxMagicDamage': 7 }, 'icon': 'sword'});
addItem(68, {'slot': 'weapon', 'type': 'dagger',  'name': 'Etched Dragon Fang', 'bonuses': {'+minDamage': 190, '+maxDamage': 286,  '+attackSpeed': 2,'+range': 1.8, '+critChance': .05, '+minMagicDamage': 9, '+maxMagicDamage': 13 }, 'icon': 'sword'});

//Fists low damage, high attack speed, melee range, low crit chance
addItem(1, {'slot': 'weapon', 'type': 'fist',  'name': 'Rock', 'bonuses': {'+minDamage': 2, '+maxDamage': 3,  '+attackSpeed': 1.5,'+range': 1, '+critChance': .03 }, 'icon': 'glove'});
addItem(2, {'slot': 'weapon', 'type': 'fist',  'name': 'Cestus', 'bonuses': {'+minDamage': 14, '+maxDamage': 20,  '+attackSpeed': 1.6,'+range': 1, '+critChance': .03 }, 'icon': 'glove'});
addItem(7, {'slot': 'weapon', 'type': 'fist',  'name': 'Bronze Weights', 'bonuses': {'+minDamage': 43, '+maxDamage': 65,  '+attackSpeed': 1.6,'+range': 1, '+critChance': .03 }, 'icon': 'glove'});
addItem(12, {'slot': 'weapon', 'type': 'fist',  'name': 'Iron Weights', 'bonuses': {'+minDamage': 62, '+maxDamage': 94,  '+attackSpeed': 1.6,'+range': 1, '+critChance': .03 }, 'icon': 'glove'});
addItem(17, {'slot': 'weapon', 'type': 'fist',  'name': 'Tekko', 'bonuses': {'+minDamage': 73, '+maxDamage': 109,  '+attackSpeed': 1.8,'+range': 1.1, '+critChance': .03 }, 'icon': 'glove'});
addItem(22, {'slot': 'weapon', 'type': 'fist',  'name': 'Iron Knuckles', 'bonuses': {'+minDamage': 90, '+maxDamage': 136,  '+attackSpeed': 1.8,'+range': 1.1, '+critChance': .03 }, 'icon': 'glove'});
addItem(27, {'slot': 'weapon', 'type': 'fist',  'name': 'Steel Knuckles', 'bonuses': {'+minDamage': 107, '+maxDamage': 161,  '+attackSpeed': 1.8,'+range': 1.1, '+critChance': .03 }, 'icon': 'glove'});
addItem(32, {'slot': 'weapon', 'type': 'fist',  'name': 'Spiked Knuckles', 'bonuses': {'+minDamage': 112, '+maxDamage': 168,  '+attackSpeed': 2,'+range': 1.2, '+critChance': .03 }, 'icon': 'glove'});
addItem(37, {'slot': 'weapon', 'type': 'fist',  'name': 'Steel Claws', 'bonuses': {'+minDamage': 128, '+maxDamage': 192,  '+attackSpeed': 2,'+range': 1.2, '+critChance': .03 }, 'icon': 'glove'});
addItem(42, {'slot': 'weapon', 'type': 'fist',  'name': 'Masterful Claws', 'bonuses': {'+minDamage': 143, '+maxDamage': 215,  '+attackSpeed': 2,'+range': 1.2, '+critChance': .03 }, 'icon': 'glove'});
addItem(47, {'slot': 'weapon', 'type': 'fist',  'name': 'Meteoric Claws', 'bonuses': {'+minDamage': 159, '+maxDamage': 239,  '+attackSpeed': 2,'+range': 1.2, '+critChance': .03 }, 'icon': 'glove'});
addItem(57, {'slot': 'weapon', 'type': 'fist',  'name': 'Runed Claws', 'bonuses': {'+minDamage': 139, '+maxDamage': 209,  '+attackSpeed': 2.5,'+range': 1.2, '+critChance': .03, '+minMagicDamage': 4, '+maxMagicDamage': 6 }, 'icon': 'glove'});
addItem(67, {'slot': 'weapon', 'type': 'fist',  'name': 'Adamantine Claws', 'bonuses': {'+minDamage': 256, '+maxDamage': 384,  '+attackSpeed': 1.5,'+range': 1.4, '+critChance': .04, '+minMagicDamage': 13, '+maxMagicDamage': 19 }, 'icon': 'glove'});

//Wands magic damage, medium attack speed, medium range, low crit chance
addItem(1, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Stick', 'bonuses': {'+minMagicDamage': 3, '+maxMagicDamage': 5,  '+attackSpeed': 1,'+range': 7, '+critChance': .03 }, 'icon': 'wand'});
addItem(5, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Balsa Wand', 'bonuses': {'+minMagicDamage': 14, '+maxMagicDamage': 22,  '+attackSpeed': 1.3,'+range': 7, '+critChance': .03 }, 'icon': 'wand'});
addItem(10, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Juniper Wand', 'bonuses': {'+minMagicDamage': 25, '+maxMagicDamage': 37,  '+attackSpeed': 1.4,'+range': 7, '+critChance': .03 }, 'icon': 'wand'});
addItem(15, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Pine Wand', 'bonuses': {'+minMagicDamage': 34, '+maxMagicDamage': 50,  '+attackSpeed': 1.5,'+range': 8, '+critChance': .03 }, 'icon': 'wand'});
addItem(20, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Rosewood Wand', 'bonuses': {'+minMagicDamage': 44, '+maxMagicDamage': 66,  '+attackSpeed': 1.5,'+range': 8, '+critChance': .03 }, 'icon': 'wand'});
addItem(25, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Rowan Wand', 'bonuses': {'+minMagicDamage': 50, '+maxMagicDamage': 76,  '+attackSpeed': 1.5,'+range': 9, '+critChance': .03 }, 'icon': 'wand'});
addItem(30, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Oak Wand', 'bonuses': {'+minMagicDamage': 60, '+maxMagicDamage': 90,  '+attackSpeed': 1.6,'+range': 9, '+critChance': .03 }, 'icon': 'wand'});
addItem(35, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Ebony Wand', 'bonuses': {'+minMagicDamage': 70, '+maxMagicDamage': 104,  '+attackSpeed': 1.6,'+range': 10, '+critChance': .03 }, 'icon': 'wand'});
addItem(40, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Ironwood Wand', 'bonuses': {'+minMagicDamage': 80, '+maxMagicDamage': 120,  '+attackSpeed': 1.6,'+range': 10, '+critChance': .03 }, 'icon': 'wand'});
addItem(45, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Intricate Wand', 'bonuses': {'+minMagicDamage': 79, '+maxMagicDamage': 119,  '+attackSpeed': 1.8,'+range': 11, '+critChance': .03 }, 'icon': 'wand'});
addItem(50, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Runed Wand', 'bonuses': {'+minMagicDamage':88, '+maxMagicDamage': 132,  '+attackSpeed': 1.8,'+range': 11, '+critChance': .03 }, 'icon': 'wand'});
addItem(60, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Adamantine Wand', 'bonuses': {'+minMagicDamage': 194, '+maxMagicDamage': 290,  '+attackSpeed': 0.9,'+range': 12, '+critChance': .03, '+minDamage': 26, '+maxDamage': 38 }, 'icon': 'wand'});
addItem(70, {'slot': 'weapon', 'type': 'wand', 'tags': ['ranged', 'magic'],  'name': 'Orichalcum Wand', 'bonuses': {'+minMagicDamage': 101, '+maxMagicDamage': 151,  '+attackSpeed': 1.9,'+range': 14, '+critChance': .04, '+minDamage': 20, '+maxDamage': 30 }, 'icon': 'wand'});

//Thrown medium damage, medium attack speed, medium range, medium crit chance
addItem(1, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Ball', 'bonuses': {'+minDamage': 2, '+maxDamage': 3,  '+attackSpeed': 1.1,'+range': 8, '+critChance': .04 }, 'icon': 'bow'});
addItem(4, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Pilum', 'bonuses': {'+minDamage': 34, '+maxDamage': 52,  '+attackSpeed': 1.1,'+range': 9, '+critChance': .04 }, 'icon': 'bow'});
addItem(9, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Knife', 'bonuses': {'+minDamage': 58, '+maxDamage': 86,  '+attackSpeed': 1.2,'+range': 9, '+critChance': .04 }, 'icon': 'bow'});
addItem(14, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Club', 'bonuses': {'+minDamage': 83, '+maxDamage': 125,  '+attackSpeed': 1.2,'+range': 10, '+critChance': .04 }, 'icon': 'bow'});
addItem(19, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Throwing Axe', 'bonuses': {'+minDamage': 109, '+maxDamage': 163,  '+attackSpeed': 1.2,'+range': 10, '+critChance': .04 }, 'icon': 'bow'});
addItem(24, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Shuriken', 'bonuses': {'+minDamage': 80, '+maxDamage': 120,  '+attackSpeed': 2,'+range': 11, '+critChance': .04 }, 'icon': 'bow'});
addItem(29, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Bolas', 'bonuses': {'+minDamage': 120, '+maxDamage': 180,  '+attackSpeed': 1.6,'+range': 11, '+critChance': .04 }, 'icon': 'bow'});
addItem(34, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Chakram', 'bonuses': {'+minDamage': 139, '+maxDamage': 209,  '+attackSpeed': 1.6,'+range': 12, '+critChance': .04 }, 'icon': 'bow'});
addItem(39, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Javelin', 'bonuses': {'+minDamage': 141, '+maxDamage': 211,  '+attackSpeed': 1.8,'+range': 12, '+critChance': .04 }, 'icon': 'bow'});
addItem(44, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Heavy Javelin', 'bonuses': {'+minDamage': 187, '+maxDamage': 281,  '+attackSpeed': 1.5,'+range': 13, '+critChance': .05 }, 'icon': 'bow'});
addItem(49, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Meteoric Javelin', 'bonuses': {'+minDamage': 208, '+maxDamage': 312,  '+attackSpeed': 1.5,'+range': 13, '+critChance': .05 }, 'icon': 'bow'});
addItem(59, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Runed Javelin', 'bonuses': {'+minDamage': 190, '+maxDamage': 286,  '+attackSpeed': 1.8,'+range': 14, '+critChance': .05, '+minMagicDamage': 6, '+maxMagicDamage': 8 }, 'icon': 'bow'});
addItem(69, {'slot': 'weapon', 'type': 'thrown', 'tags': ['ranged', 'throwing'], 'name': 'Adamantine Javelin', 'bonuses': {'+minDamage': 415, '+maxDamage': 623,  '+attackSpeed': .9,'+range': 15, '+critChance': .07, '+minMagicDamage': 20, '+maxMagicDamage': 30 }, 'icon': 'bow'});

// Two handed ranged weapons, Bows and Crossbows.
addItem(2, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Primitive Bow', 'bonuses': {'+minDamage': 14, '+maxDamage': 16,  '+attackSpeed': 1, '+range': 9, '+critChance': .03 }, 'icon': 'bow'});
addItem(7, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Short Bow', 'bonuses': {'+minDamage': 60, '+maxDamage': 70,  '+attackSpeed': 1.1, '+range': 10, '+critChance': .04 }, 'icon': 'bow'});
addItem(12, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Recurve Bow', 'bonuses': {'+minDamage': 110, '+maxDamage': 126,  '+attackSpeed': 1.1, '+range': 12, '+critChance': .04 }, 'icon': 'bow'});
addItem(17, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Long Bow', 'bonuses': {'+minDamage': 174, '+maxDamage': 200,  '+attackSpeed': 1, '+range': 14, '+critChance': .04 }, 'icon': 'bow'});
addItem(22, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Crossbow', 'bonuses': {'+minDamage': 228, '+maxDamage': 262,  '+attackSpeed': 1, '+range': 13, '+critChance': .04 }, 'icon': 'bow'});
addItem(27, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Composite Bow', 'bonuses': {'+minDamage': 256, '+maxDamage': 294,  '+attackSpeed': 1.1, '+range': 14, '+critChance': .04 }, 'icon': 'bow'});
addItem(32, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Repeating Crossbow', 'bonuses': {'+minDamage': 168, '+maxDamage': 192,  '+attackSpeed': 2, '+range': 12, '+critChance': .04 }, 'icon': 'bow'});
addItem(37, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Recurve Crossbow', 'bonuses': {'+minDamage': 350, '+maxDamage': 402,  '+attackSpeed': 1.1, '+range': 14, '+critChance': .05 }, 'icon': 'bow'});
addItem(42, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Arbalest', 'bonuses': {'+minDamage': 439, '+maxDamage': 503,  '+attackSpeed': 1, '+range': 17, '+critChance': .05 }, 'icon': 'bow'});
addItem(47, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Compound Bow', 'bonuses': {'+minDamage': 410, '+maxDamage': 470,  '+attackSpeed': 1.2, '+range': 18, '+critChance': .05 }, 'icon': 'bow'});
addItem(52, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Compound Crossbow', 'bonuses': {'+minDamage': 544, '+maxDamage': 626,  '+attackSpeed': 1, '+range': 18, '+critChance': .05 }, 'icon': 'bow'});
addItem(62, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Adamantine Crossbow', 'bonuses': {'+minDamage': 845, '+maxDamage': 973,  '+attackSpeed': 0.7, '+range': 20, '+critChance': .06, '+minMagicDamage': 26, '+maxMagicDamage': 40 }, 'icon': 'bow'});
addItem(72, {'slot': 'weapon', 'type': 'bow', 'tags': ['twoHanded', 'ranged'], 'name': 'Dragonbone Greatbow', 'bonuses': {'+minDamage': 657, '+maxDamage': 757,  '+attackSpeed': 1, '+range': 20, '+critChance': .06, '+minMagicDamage': 38, '+maxMagicDamage': 56 }, 'icon': 'bow'});

//Staffs
//addItem(2, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Branch', 'bonuses': {'+minDamage': 5, '+maxDamage': 7, '+minMagicDamage': 2, '+maxMagicDamage': 4, '+attackSpeed': 1, '+range': 1.8, '+critChance': .03 }, 'icon': 'wand'});
addItem(3, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Balsa Staff', 'bonuses': {'+minDamage': 26, '+maxDamage': 30, '+minMagicDamage': 13, '+maxMagicDamage': 15, '+attackSpeed': 1.2, '+range': 2, '+critChance': .03 }, 'icon': 'wand'});
addItem(8, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Juniper Staff', 'bonuses': {'+minDamage': 45, '+maxDamage': 55, '+minMagicDamage': 23, '+maxMagicDamage': 27, '+attackSpeed': 1.2, '+range': 2, '+critChance': .04 }, 'icon': 'wand'});
addItem(13, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Pine Staff', 'bonuses': {'+minDamage': 65, '+maxDamage': 79, '+minMagicDamage': 33, '+maxMagicDamage': 39, '+attackSpeed': 1.2, '+range': 2, '+critChance': .04 }, 'icon': 'wand'});
addItem(18, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Rosewood Quarterstaff', 'bonuses': {'+minDamage': 86, '+maxDamage': 104, '+minMagicDamage': 43, '+maxMagicDamage': 51, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .04 }, 'icon': 'wand'});
addItem(23, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Rowan Quarterstaff', 'bonuses': {'+minDamage': 106, '+maxDamage': 128, '+minMagicDamage': 53, '+maxMagicDamage': 63, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .04 }, 'icon': 'wand'});
addItem(28, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Oak Quarterstaff', 'bonuses': {'+minDamage': 126, '+maxDamage': 154, '+minMagicDamage': 63, '+maxMagicDamage': 77, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .04 }, 'icon': 'wand'});
addItem(33, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Ebony Quarterstaff', 'bonuses': {'+minDamage': 145, '+maxDamage': 177, '+minMagicDamage': 72, '+maxMagicDamage': 88, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .05 }, 'icon': 'wand'});
addItem(38, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Ironwood Quarterstaff', 'bonuses': {'+minDamage': 165, '+maxDamage': 201, '+minMagicDamage': 82, '+maxMagicDamage': 100, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .05 }, 'icon': 'wand'});
addItem(43, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Iron Quarterstaff', 'bonuses': {'+minDamage': 183, '+maxDamage': 223, '+minMagicDamage': 91, '+maxMagicDamage': 111, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .06 }, 'icon': 'wand'});
addItem(48, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Steel Quarterstaff', 'bonuses': {'+minDamage': 203, '+maxDamage': 247, '+minMagicDamage': 101, '+maxMagicDamage': 123, '+attackSpeed': 1.2, '+range': 2.5, '+critChance': .06 }, 'icon': 'wand'});
addItem(58, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Adamantine Quarterstaff', 'bonuses': {'+minDamage': 331, '+maxDamage': 403, '+minMagicDamage': 168, '+maxMagicDamage': 204, '+attackSpeed': 0.8, '+range': 3, '+critChance': .07 }, 'icon': 'wand'});
addItem(68, {'slot': 'weapon', 'type': 'staff', 'tags': ['twoHanded', 'magic'], 'name': 'Orichalcum Quarterstaff', 'bonuses': {'+minDamage': 225, '+maxDamage': 273, '+minMagicDamage': 112, '+maxMagicDamage': 136, '+attackSpeed': 1.5, '+range': 3, '+critChance': .07 }, 'icon': 'wand'});

//Two Handed Axes and Polearms
addItem(2, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Pickaxe', 'bonuses': {'+minDamage': 25, '+maxDamage': 31,  '+attackSpeed': 0.5, '+range': 2, '+critChance': .05 }, 'icon': 'axe'});
addItem(7, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Felling Axe', 'bonuses': {'+minDamage': 79, '+maxDamage': 97,  '+attackSpeed': 0.8, '+range': 2, '+critChance': .06 }, 'icon': 'axe'});
addItem(12, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Scythe', 'bonuses': {'+minDamage': 143, '+maxDamage': 175,  '+attackSpeed': 0.8, '+range': 3, '+critChance': .06 }, 'icon': 'axe'});
addItem(17, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Greataxe', 'bonuses': {'+minDamage': 164, '+maxDamage': 200,  '+attackSpeed': 1, '+range': 3, '+critChance': .07 }, 'icon': 'axe'});
addItem(22, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Heavy Greataxe', 'bonuses': {'+minDamage': 214, '+maxDamage': 262,  '+attackSpeed': 1, '+range': 3, '+critChance': .07 }, 'icon': 'axe'});
addItem(27, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Naginata', 'bonuses': {'+minDamage': 240, '+maxDamage': 294,  '+attackSpeed': 1.1, '+range': 4, '+critChance': .07 }, 'icon': 'axe'});
addItem(32, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Voulge', 'bonuses': {'+minDamage': 283, '+maxDamage': 347,  '+attackSpeed': 1.1, '+range': 4, '+critChance': .08 }, 'icon': 'axe'});
addItem(37, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Glaive', 'bonuses': {'+minDamage': 330, '+maxDamage': 402,  '+attackSpeed': 1.1, '+range': 4, '+critChance': .08 }, 'icon': 'axe'});
addItem(42, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Iron Halberd', 'bonuses': {'+minDamage': 340, '+maxDamage': 416,  '+attackSpeed': 1.2, '+range': 5, '+critChance': .09 }, 'icon': 'axe'});
addItem(47, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Steel Halberd', 'bonuses': {'+minDamage': 382, '+maxDamage': 466,  '+attackSpeed': 1.2, '+range': 5, '+critChance': .09 }, 'icon': 'axe'});
addItem(52, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Poleaxe', 'bonuses': {'+minDamage': 387, '+maxDamage': 473,  '+attackSpeed': 1.3, '+range': 6, '+critChance': .1 }, 'icon': 'axe'});
addItem(62, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Runed Poleaxe', 'bonuses': {'+minDamage': 425, '+maxDamage': 519,  '+attackSpeed': 1.3, '+range': 6, '+critChance': .1, '+minMagicDamage': 10, '+maxMagicDamage': 24 }, 'icon': 'axe'});
addItem(72, {'slot': 'weapon', 'type': 'polearm', 'tags': ['twoHanded'], 'name': 'Adamantine Poleaxe', 'bonuses': {'+minDamage': 1014, '+maxDamage': 1238,  '+attackSpeed': 0.6, '+range': 6, '+critChance': .11, '+minMagicDamage': 50, '+maxMagicDamage': 100 }, 'icon': 'axe'});

//Greatswords
//addItem(2, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Corroded Claymore', 'bonuses': {'+minDamage': 16, '+maxDamage': 20, '+attackSpeed': 0.8, '+range': 2, '+critChance': .04 }, 'icon': 'sword'});
addItem(6, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Copper Claymore', 'bonuses': {'+minDamage': 64, '+maxDamage': 78, '+attackSpeed': 1, '+range': 2, '+critChance': .05 }, 'icon': 'sword'});
addItem(11, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Bronze Claymore', 'bonuses': {'+minDamage': 116, '+maxDamage': 140, '+attackSpeed': 1, '+range': 2, '+critChance': .05 }, 'icon': 'sword'});
addItem(16, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Iron Claymore', 'bonuses': {'+minDamage': 167, '+maxDamage': 203, '+attackSpeed': 1, '+range': 2, '+critChance': .05 }, 'icon': 'sword'});
addItem(21, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Black Greatsword', 'bonuses': {'+minDamage': 180, '+maxDamage': 220, '+attackSpeed': 1.2, '+range': 3, '+critChance': .06 }, 'icon': 'sword'});
addItem(26, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Katana', 'bonuses': {'+minDamage': 223, '+maxDamage': 271, '+attackSpeed': 1.2, '+range': 3, '+critChance': .06 }, 'icon': 'sword'});
addItem(31, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Forged Greatsword', 'bonuses': {'+minDamage': 265, '+maxDamage': 323, '+attackSpeed': 1.2, '+range': 3, '+critChance': .06 }, 'icon': 'sword'});
addItem(36, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Steel Greatsword', 'bonuses': {'+minDamage': 307, '+maxDamage': 375, '+attackSpeed': 1.2, '+range': 3, '+critChance': .06 }, 'icon': 'sword'});
addItem(41, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Stainless Greatsword', 'bonuses': {'+minDamage': 350, '+maxDamage': 428, '+attackSpeed': 1.2, '+range': 3, '+critChance': .06 }, 'icon': 'sword'});
addItem(46, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Bidenhander', 'bonuses': {'+minDamage': 336, '+maxDamage': 410, '+attackSpeed': 1.4, '+range': 3.5, '+critChance': .06 }, 'icon': 'sword'});
addItem(51, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Meteoric Bidenhander', 'bonuses': {'+minDamage': 373, '+maxDamage': 465, '+attackSpeed': 1.4, '+range': 3.5, '+critChance': .06 }, 'icon': 'sword'});
addItem(61, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Adamantine Bidenhander', 'bonuses': {'+minDamage': 710, '+maxDamage': 866, '+attackSpeed': 0.8, '+range': 3.5, '+critChance': .07, '+minMagicDamage': 25, '+maxMagicDamage': 33 }, 'icon': 'sword'});
addItem(71, {'slot': 'weapon', 'type': 'greatsword', 'tags': ['twoHanded'], 'name': 'Masterwork Katana', 'bonuses': {'+minDamage': 421, '+maxDamage': 513, '+attackSpeed': 1.5, '+range': 4, '+critChance': .07, '+minMagicDamage': 26, '+maxMagicDamage': 36 }, 'icon': 'sword'});